import type { SoundCategory } from "./types";

export const soundCategories: SoundCategory[] = [
  {
    id: "instruments",
    name: "がっき",
    emoji: "🎵",
    color: "from-purple-400 to-pink-500",
    sounds: [
      {
        id: "piano",
        name: "ピアノ",
        emoji: "🎹",
        audioFile: "/sounds/piano.mp3",
        description: "きれいな おとの ピアノ",
        category: "instrument",
      },
      {
        id: "guitar",
        name: "ギター",
        emoji: "🎸",
        audioFile: "/sounds/guitar.mp3",
        description: "やさしい おとの ギター",
        category: "instrument",
      },
      {
        id: "drum",
        name: "ドラム",
        emoji: "🥁",
        audioFile: "/sounds/drum.mp3",
        description: "げんきな おとの ドラム",
        category: "instrument",
      },
      {
        id: "flute",
        name: "フルート",
        emoji: "🪈",
        audioFile: "/sounds/flute.mp3",
        description: "やわらかい おとの フルート",
        category: "instrument",
      },
      {
        id: "violin",
        name: "バイオリン",
        emoji: "🎻",
        audioFile: "/sounds/violin.mp3",
        description: "うつくしい おとの バイオリン",
        category: "instrument",
      },
      {
        id: "trumpet",
        name: "トランペット",
        emoji: "🎺",
        audioFile: "/sounds/trumpet.mp3",
        description: "あかるい おとの トランペット",
        category: "instrument",
      },
    ],
  },
  {
    id: "animals",
    name: "どうぶつ",
    emoji: "🐾",
    color: "from-green-400 to-blue-500",
    sounds: [
      {
        id: "cat",
        name: "ねこ",
        emoji: "🐱",
        audioFile: "/sounds/cat.mp3",
        description: "ねこの なきごえ にゃーにゃー",
        category: "animal",
      },
      {
        id: "dog",
        name: "いぬ",
        emoji: "🐶",
        audioFile: "/sounds/dog.mp3",
        description: "いぬの なきごえ わんわん",
        category: "animal",
      },
      {
        id: "cow",
        name: "うし",
        emoji: "🐄",
        audioFile: "/sounds/cow.mp3",
        description: "うしの なきごえ もーもー",
        category: "animal",
      },
      {
        id: "bird",
        name: "とり",
        emoji: "🐦",
        audioFile: "/sounds/bird.mp3",
        description: "とりの なきごえ ちゅんちゅん",
        category: "animal",
      },
      {
        id: "elephant",
        name: "ぞう",
        emoji: "🐘",
        audioFile: "/sounds/elephant.mp3",
        description: "ぞうの なきごえ ぱおーん",
        category: "animal",
      },
      {
        id: "lion",
        name: "らいおん",
        emoji: "🦁",
        audioFile: "/sounds/lion.mp3",
        description: "らいおんの なきごえ がおー",
        category: "animal",
      },
    ],
  },
  {
    id: "nature",
    name: "しぜん",
    emoji: "🌿",
    color: "from-emerald-400 to-teal-500",
    sounds: [
      {
        id: "rain",
        name: "あめ",
        emoji: "🌧️",
        audioFile: "/sounds/rain.mp3",
        description: "あめの おと ぽつぽつ",
        category: "nature",
      },
      {
        id: "wind",
        name: "かぜ",
        emoji: "💨",
        audioFile: "/sounds/wind.mp3",
        description: "かぜの おと ひゅーひゅー",
        category: "nature",
      },
      {
        id: "ocean",
        name: "うみ",
        emoji: "🌊",
        audioFile: "/sounds/ocean.mp3",
        description: "なみの おと ざざーん",
        category: "nature",
      },
      {
        id: "thunder",
        name: "かみなり",
        emoji: "⚡",
        audioFile: "/sounds/thunder.mp3",
        description: "かみなりの おと ごろごろ",
        category: "nature",
      },
      {
        id: "fire",
        name: "たき火",
        emoji: "🔥",
        audioFile: "/sounds/fire.mp3",
        description: "たき火の おと ぱちぱち",
        category: "nature",
      },
    ],
  },
  {
    id: "transport",
    name: "のりもの",
    emoji: "🚗",
    color: "from-yellow-400 to-red-500",
    sounds: [
      {
        id: "car",
        name: "くるま",
        emoji: "🚗",
        audioFile: "/sounds/car.mp3",
        description: "くるまの おと ぶーぶー",
        category: "transport",
      },
      {
        id: "train",
        name: "でんしゃ",
        emoji: "🚆",
        audioFile: "/sounds/train.mp3",
        description: "でんしゃの おと がたんごとん",
        category: "transport",
      },
      {
        id: "airplane",
        name: "ひこうき",
        emoji: "✈️",
        audioFile: "/sounds/airplane.mp3",
        description: "ひこうきの おと ごーっ",
        category: "transport",
      },
      {
        id: "ship",
        name: "ふね",
        emoji: "🚢",
        audioFile: "/sounds/ship.mp3",
        description: "ふねの おと ぼーっ",
        category: "transport",
      },
      {
        id: "helicopter",
        name: "ヘリコプター",
        emoji: "🚁",
        audioFile: "/sounds/helicopter.mp3",
        description: "ヘリコプターの おと ばたばた",
        category: "transport",
      },
    ],
  },
];

export const encouragementMessages = [
  "🎵 いい おとだね！",
  "👂 よく きけたね！",
  "🎶 おんがく だいすき！",
  "✨ すてきな おと！",
  "🌟 じょうずに きけたね！",
  "🎉 もっと きいてみよう！",
];

export const completionMessages = [
  "🎵 たくさんの おとを きいたね！",
  "👂 みみが とても よくなったね！",
  "🎶 おんがく マスターだね！",
  "🌟 ぜんぶの おと コンプリート！",
];
