import type { TypingLesson } from "./types";

export const typingLessons: TypingLesson[] = [
  {
    id: "hiragana-a",
    title: "あいうえお",
    description: "きほんの ひらがなを うとう",
    targetText: "あいうえお",
    level: "beginner",
    icon: "🌸",
  },
  {
    id: "hiragana-ka",
    title: "かきくけこ",
    description: "か ぎょうを うとう",
    targetText: "かきくけこ",
    level: "beginner",
    icon: "🍎",
  },
  {
    id: "hiragana-sa",
    title: "さしすせそ",
    description: "さ ぎょうを うとう",
    targetText: "さしすせそ",
    level: "beginner",
    icon: "🐟",
  },
  {
    id: "simple-words",
    title: "かんたんな ことば",
    description: "みじかい ことばを うとう",
    targetText: "いぬ ねこ とり",
    level: "beginner",
    icon: "🐕",
  },
  {
    id: "greetings",
    title: "あいさつ",
    description: "あいさつの ことばを うとう",
    targetText: "おはよう",
    level: "intermediate",
    icon: "☀️",
  },
  {
    id: "thanks",
    title: "ありがとう",
    description: "かんしゃの きもちを つたえよう",
    targetText: "ありがとう",
    level: "intermediate",
    icon: "🙏",
  },
  {
    id: "name",
    title: "なまえ",
    description: "じぶんの なまえを かこう",
    targetText: "わたしのなまえ",
    level: "intermediate",
    icon: "✏️",
  },
  {
    id: "numbers",
    title: "すうじ",
    description: "すうじを うとう",
    targetText: "1 2 3 4 5",
    level: "intermediate",
    icon: "🔢",
  },
  {
    id: "days",
    title: "ようび",
    description: "いっしゅうかんの ようびを うとう",
    targetText: "げつようび",
    level: "advanced",
    icon: "📅",
  },
  {
    id: "sentence",
    title: "ぶんしょう",
    description: "みじかい ぶんを うとう",
    targetText: "きょうは いいてんき",
    level: "advanced",
    icon: "📝",
  },
];
