import type { TypingCourse, TypingLesson } from "./types";

// コース定義
export const typingCourses: TypingCourse[] = [
  {
    id: "animals",
    title: "どうぶつ",
    description: "みぢかな どうぶつの なまえを うとう",
    icon: "🐕",
    order: 1,
    color: "from-green-400 to-blue-500",
  },
  {
    id: "family",
    title: "かぞく",
    description: "かぞくの なまえを うとう",
    icon: "👨‍👩‍👧‍👦",
    order: 2,
    color: "from-pink-400 to-red-500",
  },
  {
    id: "food",
    title: "たべもの",
    description: "すきな たべものを うとう",
    icon: "🍎",
    order: 3,
    color: "from-yellow-400 to-orange-500",
  },
  {
    id: "basic",
    title: "きほん",
    description: "ひらがなの きほんを おぼえよう",
    icon: "🌸",
    order: 4,
    color: "from-purple-400 to-pink-500",
  },
  {
    id: "practice",
    title: "れんしゅう",
    description: "て の つかいかたを れんしゅう",
    icon: "✋",
    order: 5,
    color: "from-indigo-400 to-purple-500",
  },
];

export const typingLessons: TypingLesson[] = [
  // どうぶつコース
  {
    id: "animal-dog",
    title: "いぬ",
    description: "いぬ って うとう",
    targetText: "いぬ",
    romajiText: "inu",
    level: "beginner",
    icon: "🐕",
    courseId: "animals",
    wordEmojis: { いぬ: "🐕" },
  },
  {
    id: "animal-cat",
    title: "ねこ",
    description: "ねこ って うとう",
    targetText: "ねこ",
    romajiText: "neko",
    level: "beginner",
    icon: "🐱",
    courseId: "animals",
    wordEmojis: { ねこ: "🐱" },
  },
  {
    id: "animal-bird",
    title: "とり",
    description: "とり って うとう",
    targetText: "とり",
    romajiText: "tori",
    level: "beginner",
    icon: "🐦",
    courseId: "animals",
    wordEmojis: { とり: "🐦" },
  },
  {
    id: "animal-rabbit",
    title: "うさぎ",
    description: "うさぎ って うとう",
    targetText: "うさぎ",
    romajiText: "usagi",
    level: "beginner",
    icon: "🐰",
    courseId: "animals",
    wordEmojis: { うさぎ: "🐰" },
  },
  {
    id: "animal-fish",
    title: "さかな",
    description: "さかな って うとう",
    targetText: "さかな",
    romajiText: "sakana",
    level: "intermediate",
    icon: "🐟",
    courseId: "animals",
    wordEmojis: { さかな: "🐟" },
  },
  {
    id: "animals-together",
    title: "どうぶつ みんな",
    description: "どうぶつの ともだちを うとう",
    targetText: "いぬ ねこ とり",
    romajiText: "inu neko tori",
    level: "intermediate",
    icon: "🐕",
    courseId: "animals",
    wordEmojis: { いぬ: "🐕", ねこ: "🐱", とり: "🐦" },
  },

  // かぞくコース
  {
    id: "family-mama",
    title: "ママ",
    description: "ママ って うとう",
    targetText: "ママ",
    romajiText: "mama",
    level: "beginner",
    icon: "👩",
    courseId: "family",
    wordEmojis: { ママ: "👩" },
  },
  {
    id: "family-papa",
    title: "パパ",
    description: "パパ って うとう",
    targetText: "パパ",
    romajiText: "papa",
    level: "beginner",
    icon: "👨",
    courseId: "family",
    wordEmojis: { パパ: "👨" },
  },
  {
    id: "family-baby",
    title: "あかちゃん",
    description: "あかちゃん って うとう",
    targetText: "あかちゃん",
    romajiText: "akachan",
    level: "intermediate",
    icon: "👶",
    courseId: "family",
    wordEmojis: { あかちゃん: "👶" },
  },

  // たべものコース
  {
    id: "food-apple",
    title: "りんご",
    description: "りんご って うとう",
    targetText: "りんご",
    romajiText: "ringo",
    level: "beginner",
    icon: "🍎",
    courseId: "food",
    wordEmojis: { りんご: "🍎" },
  },
  {
    id: "food-banana",
    title: "バナナ",
    description: "バナナ って うとう",
    targetText: "バナナ",
    romajiText: "banana",
    level: "beginner",
    icon: "🍌",
    courseId: "food",
    wordEmojis: { バナナ: "🍌" },
  },
  {
    id: "food-bread",
    title: "パン",
    description: "パン って うとう",
    targetText: "パン",
    romajiText: "pan",
    level: "beginner",
    icon: "🍞",
    courseId: "food",
    wordEmojis: { パン: "🍞" },
  },

  // きほんコース (基本のひらがな)
  {
    id: "hiragana-a",
    title: "あいうえお",
    description: "きほんの ひらがなを うとう",
    targetText: "あいうえお",
    romajiText: "aiueo",
    level: "beginner",
    icon: "🌸",
    courseId: "basic",
  },
  {
    id: "hiragana-ka",
    title: "かきくけこ",
    description: "か ぎょうを うとう",
    targetText: "かきくけこ",
    romajiText: "kakikukeko",
    level: "beginner",
    icon: "🌺",
    courseId: "basic",
  },
  {
    id: "hiragana-sa",
    title: "さしすせそ",
    description: "さ ぎょうを うとう",
    targetText: "さしすせそ",
    romajiText: "sasisuseso",
    level: "beginner",
    icon: "🌻",
    courseId: "basic",
  },
  {
    id: "greetings",
    title: "あいさつ",
    description: "あいさつの ことばを うとう",
    targetText: "おはよう",
    romajiText: "ohayou",
    level: "intermediate",
    icon: "☀️",
    courseId: "basic",
  },
  {
    id: "thanks",
    title: "ありがとう",
    description: "かんしゃの きもちを つたえよう",
    targetText: "ありがとう",
    romajiText: "arigatou",
    level: "intermediate",
    icon: "🙏",
    courseId: "basic",
  },
  {
    id: "numbers",
    title: "すうじ",
    description: "かんたんな すうじを うとう",
    targetText: "1 2 3",
    romajiText: "1 2 3",
    level: "beginner",
    icon: "🔢",
    courseId: "basic",
  },

  // れんしゅうコース (手の使い分け練習)
  {
    id: "left-hand-vowels",
    title: "ひだりて あえ",
    description: "ひだりてで あ と え を うとう",
    targetText: "あ え あ え",
    romajiText: "a e a e",
    level: "beginner",
    icon: "🫷",
    courseId: "practice",
  },
  {
    id: "right-hand-vowels",
    title: "みぎて いうお",
    description: "みぎてで い う お を うとう",
    targetText: "い う お い う お",
    romajiText: "i u o i u o",
    level: "beginner",
    icon: "🫸",
    courseId: "practice",
  },
  {
    id: "both-hands-aiueo",
    title: "りょうて あいうえお",
    description: "りょうてで あいうえお を うとう",
    targetText: "あいうえお",
    romajiText: "aiueo",
    level: "intermediate",
    icon: "👐",
    courseId: "practice",
  },
];
